name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: [master]

jobs:
  build:
    uses: dbeaver/dbeaver-common/.github/workflows/mvn-package.yml@devel
    name: Check
    secrets: inherit
    with:
      project-deps: ./eclipse-bundle-azure/project.deps
      project-directory: ./eclipse-bundle-azure/aggregate
      timeout-minutes: 2

  lint:
    uses: dbeaver/dbeaver-common/.github/workflows/java-checkstyle.yml@devel
    name: Check
    secrets: inherit