name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: [devel]

jobs:
  build:
    uses: ./.github/workflows/verify.yaml
    with:
      project-directory: ./dbeaver-deps-ce
