name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: [devel]

jobs:
  build-java:
    uses: dbeaver/dbeaver-common/.github/workflows/mvn-package.yml@devel
    name: Build
    secrets: inherit
    with:
      project-deps: ./dbeaver-deps-ce/project.deps
      timeout-minutes: 10
  check-deps:
    name: Submit Dependency Snapshot
    uses: advanced-security/maven-dependency-submission-action@v3
