name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: [devel]

jobs:
  build-java:
    uses: dbeaver/dbeaver-common/.github/workflows/mvn-package.yml@devel
    name: Build
    secrets: inherit
    permissions:
      contents: read
    with:
      project-deps: ./dbeaver-deps-ce/project.deps
      timeout-minutes: 10
